# src/06_generate_insights.py
import pandas as pd
import os
import datetime

ROOT = os.path.dirname(os.path.dirname(__file__))
FEATURE_DIR = os.path.join(ROOT, "data", "features")
REPORT_PATH = os.path.join(ROOT, "INSIGHTS_REPORT.md")

def generate_insights():
    print("📝 Generating Insights Report...")
    
    inv_path = os.path.join(FEATURE_DIR, "inventory_recommendations.csv")
    if not os.path.exists(inv_path):
        print("❌ No inventory recommendations found. Run pipeline first.")
        return

    df = pd.read_csv(inv_path)
    
    # Sort by Recommended Order Qty (High to Low)
    top_items = df.sort_values("RecommendedOrderQty", ascending=False).head(5)
    
    # Sort by Trend Score (High to Low)
    trending = df.sort_values("TrendScore", ascending=False).head(3)
    
    today = datetime.datetime.now().strftime("%Y-%m-%d")
    
    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write(f"# 🧥 Kathmandu Fashion Forecast - Executive Summary\n")
        f.write(f"**Date:** {today}\n\n")
        
        f.write("## 🚀 Top Buying Recommendations\n")
        f.write("Based on AI predictive modeling (Sales + Social + Search + Psychology):\n\n")
        
        for _, row in top_items.iterrows():
            cat = row['Category']
            qty = row['RecommendedOrderQty']
            risk = row['RiskLevel']
            persona = row['PersonaTarget']
            reason = f"High demand expected from **{persona}** groups."
            if row['TrendScore'] > 7:
                reason += " Currently viral on social media."
            
            f.write(f"### 1. {cat} (Order: {qty} units)\n")
            f.write(f"- **Risk Level:** {risk}\n")
            f.write(f"- **Target Persona:** {persona}\n")
            f.write(f"- **Why?** {reason}\n\n")
            
        f.write("---\n\n")
        
        f.write("## 🔥 Emerging Trends (Social Signals)\n")
        f.write("These items have high social buzz but may not have historical sales yet:\n\n")
        for _, row in trending.iterrows():
            if row['Category'] not in top_items['Category'].values:
                f.write(f"- **{row['Category']}**: Trend Score {row['TrendScore']}/10. Keep an eye on this.\n")
        
        f.write("\n\n---\n")
        f.write("> **System Note:** This report was auto-generated by your AI Fashion Forecaster.")
        
    print(f"✅ Insights generated: {REPORT_PATH}")

if __name__ == "__main__":
    generate_insights()
